name: optional
version: 6.0.0-nullsafety.1
description: An implementation of the Optional type, which helps avoid dealing with null references
homepage: https://github.com/tonio-ramirez/optional.dart
repository: https://github.com/tonio-ramirez/optional.dart
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  collection: ^1.15.0
dev_dependencies:
  mockito: '>=5.0.0 <6.0.0'
  test: ^1.16.5
  pedantic: ^1.11.0
  build_runner: '>=1.10.0 <2.0.0'
#  test_coverage: '^0.5.0'
