name: optional
version: 4.0.1
description: An implementation of the Optional type, which helps avoid dealing with null references
homepage: https://github.com/tonio-ramirez/optional.dart
repository: https://github.com/tonio-ramirez/optional.dart
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  collection: '^1.14.11'
dev_dependencies:
  mockito: '>=2.2.0 <4.0.0'
  test: '>=0.12.0 <2.0.0'
  pedantic: '^1.0.0'
  test_coverage: '^0.4.0'