name: optional
version: 2.0.0
author: Juan Antonio Ramirez <tonior@gmail.com>
description: An implementation of the Optional type
homepage: https://github.com/tonio-ramirez/optional.dart
dev_dependencies:
  mockito: ^2.0.0
  test: ^0.12.0
