name: optional
version: 1.2.3+1
author: Juan Antonio Ramirez <tonior@gmail.com>
description: An implementation of the Optional type
homepage: https://github.com/tonio-ramirez/optional.dart
dev_dependencies:
  mock: '>=0.12.0 <0.13.0'
  unittest: '>=0.12.0 <0.13.0'
