name: optional
version: 3.0.2
author: Juan Antonio Ramirez <tonior@gmail.com>
description: An implementation of the Optional type, which helps avoid dealing with null references
homepage: https://github.com/tonio-ramirez/optional.dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  mockito: '>=2.2.0 <4.0.0'
  test: '>=0.12.0 <2.0.0'
